# config/platform.yaml
# De minimale, fundamentele configuratie voor S1mpleTrader V2.

language: 'en'
plugins_root_path: 'plugins'

data:
  source_dir: 'source_data'

portfolio:
  initial_capital: 10000.0

logging:
  profile: 'analysis'
  profiles:
    developer: ['WARNING', 'ERROR', 'CRITICAL']
    analysis: ['DEBUG', 'INFO', 'MATCH', 'FILTER', 'TRADE', 'RESULT', 'WARNING', 'ERROR', 'CRITICAL']
