# config/portfolio.yaml
# Example portfolio configuration demonstrating the layered risk management system
#
# ARCHITECTURAL NOTE: Single Source of Truth for Risk Configuration
# - StrategyLink: ONLY contains strategy_blueprint_path and execution_environment_id
# - RiskPolicy.strategy_rules: SINGLE SOURCE OF TRUTH for all strategy risk configuration
# - This separation ensures no duplication and centralized risk management

display_name: "Main Trading Portfolio"
description: "Primary portfolio for EUR-based crypto trading strategies with comprehensive risk management"

strategies:
  - strategy_blueprint_path: "runs/mss_fvg_strategy.yaml"
    execution_environment_id: "backtest_btc_eur"

  - strategy_blueprint_path: "runs/eth_mean_reversion.yaml"
    execution_environment_id: "backtest_eth_eur"

  - strategy_blueprint_path: "runs/multi_timeframe_momentum.yaml"
    execution_environment_id: "backtest_multi_asset"

risk_policy:
  # Portfolio-wide risk rules
  portfolio_rules:
    max_total_drawdown_pct: 25.0  # Emergency stop if portfolio loses 25%
    max_position_size_pct_per_strategy: 15.0  # No strategy can have >15% portfolio exposure
    max_correlated_positions: 3  # Maximum 3 positions in correlated assets

  # Strategy-specific risk rules (single source of truth)
  strategy_rules:
    mss_fvg_strategy:
      capital_allocation:
        percentage: 50.0  # 50% of portfolio capital
        max_quote_amount: 25000.0  # Maximum €25,000
      max_drawdown_pct: 15.0  # Stop strategy if it loses 15%
      max_position_size_pct: 10.0  # Max 10% of strategy allocation per position
      enabled: true

    eth_mean_reversion:
      capital_allocation:
        percentage: 30.0  # 30% of portfolio capital
        max_quote_amount: 15000.0  # Maximum €15,000
      max_drawdown_pct: 12.0  # Lower risk tolerance for ETH strategy
      max_position_size_pct: 8.0  # Smaller positions for ETH
      enabled: true

    multi_timeframe_momentum:
      capital_allocation:
        percentage: 20.0  # 20% of portfolio capital
        max_quote_amount: 10000.0  # Maximum €10,000
      max_drawdown_pct: 10.0  # Conservative risk management
      max_position_size_pct: 5.0  # Smallest position sizes
      enabled: false  # Disabled for now

  # Strategy-specific risk rules (already defined above in each strategy)

  # Event-driven risk responses
  event_responses:
    # Response to maximum drawdown breach
    "MAX_DRAWDOWN_BREACHED":
      block_new_signals_min: 1440  # Block all new signals for 24 hours
      close_all_portfolio_positions: true  # Emergency close all positions
      cancel_all_entry_orders_portfolio: true  # Cancel all pending orders
      notification_message: "EMERGENCY: Maximum drawdown breached. All positions closed."

    # Response to strategy-specific drawdown
    "STRATEGY_DRAWDOWN_EXCEEDED":
      block_new_signals_min: 60  # Block signals for 1 hour for affected strategy
      reduce_position_size_pct_strategy: 50.0  # Reduce position sizes by 50%
      move_sl_to_breakeven_strategy: true  # Move stop losses to breakeven
      notification_message: "WARNING: Strategy {strategy_name} exceeded maximum drawdown."

    # Response to correlation breach
    "CORRELATION_LIMIT_EXCEEDED":
      block_new_signals_min: 30  # Brief pause to reassess
      cancel_entry_orders_strategy: true  # Cancel pending entries for affected strategy
      notification_message: "WARNING: Too many correlated positions for strategy {strategy_name}."

    # Response to rapid market movement
    "RAPID_PRICE_MOVEMENT":
      block_new_signals_min: 15  # Brief pause during volatility
      notification_message: "WARNING: Rapid price movement detected. Signals temporarily blocked."

    # Response to portfolio correlation warning
    "PORTFOLIO_CORRELATION_HIGH":
      reduce_position_size_pct_strategy: 25.0  # Reduce all strategy positions by 25%
      notification_message: "WARNING: High correlation detected across portfolio strategies."